### PR TITLE
fix: use different cache location when on netfs

### LINKED ISSUE #5439: "File still doesn't exist" error during conda-pypi mapping fetch
## Problem

Pixi fails to fetch the conda-pypi mapping with a cryptic error.

Copilot suggested the problem is that the cache directory isn't created via `create_dir_all` before use, but I don't think that's right. I tried manually creating the directory (see Workaround section), and it didn't fix anything.

The error:
```
>pixi update
failed to map conda packages to their PyPI equivalents. This mapping is required when using PyPI dependencies alongside conda packages.
  ├─▶ failed to fetch conda-pypi mapping from remote source
  ├─▶ File still doesn't exist
  ╰─▶ No such file or directory (os error 2)
```

## Steps to Reproduce
1. Attempt to run any pixi command in a project with pypi dependency or with pyproject.toml 
2. Observe failure and error about missing file or directory

## Workaround
Changing the cache location works:
```bash
PIXI_CACHE_DIR=/tmp/pixi-test-cache pixi update
```

But manually creating the directory does **NOT** work:
```bash
mkdir -p ~/.cache/rattler/conda-pypi-mapping
```

## Environment
- Pixi version: 0.63.2
- OS: CentOS Linux
- How was Pixi installed: curl

### PR DESCRIPTION
**Pull request by nichmor**
### Description

This fix aims to detect if pixi is running on some HPC file and redirect to a different cache folder. Also adds configuration to modify where the cache will be stored

Fixes https://github.com/prefix-dev/pixi/issues/5439

### How Has This Been Tested?

I've tried to use a userspace NFS server (nfs-ganesha) on my mac to reproduce the issue, but unfortunatly I'm not able to.

### AI Disclosure

- [x] This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: {e.g., Claude, Codex, GitHub Copilot, ChatGPT, etc.}

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added sufficient tests to cover my changes.
- [ ] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

**Comment by baszalmstra** [comment]
This is a pretty cool approach!

I think when using HPC, some cache paths should come from the HPC fs, like the package cache! But the pypi-mapping and other more "temporary" caches probably shouldnt be used from there. It would at least be nice if users have a way to configure this. 

Also, Im wondering if it would be possible to configure this through `config.toml` and not only through environment variables.

File: crates/pixi_config/src/lib.rs [hunk 1]
```diff
@@ -3023,4 +3500,272 @@ UNUSED = "unused"
             }
         );
     }
+
+    // Serialize env-var-sensitive tests so they don't race against each other.
+    // Parallel cargo-test threads share the process environment, and
+    // cache_dir_for / is_network_filesystem read several env vars.
+    static NETFS_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
+
+    struct ScopedEnv {
```
Comment (baszalmstra) [inline crates/pixi_config/src/lib.rs:3552]: I think we have a crate to do this. temp-env or something like that.

**Review by baszalmstra — COMMENTED** [review]
Looks good! The only thing Im missing is environment variables to override some of these settings.

**Review by baszalmstra — APPROVED** [review]

**Comment by Vyrolan** [comment]
For the record, this new functionality does not actually work at all...at least not for the conda packages cache.   If I set the `cache.conda-packages` in my config toml and/or set the `PIXI_CACHE_CONDA_PACKAGES_DIR` environment variable, it has absolutely no effect on where the conda packages are cached.   The only thing it DOES seem to impact is the `pixi clean` command.   If you set the environment variable and then do several `pixi install` that should cache many conda packages, nothing will ever appear in the configured cache dir...but then running `pixi clean cache --conda` will claim the cache was already clean because the clean seems to be the only thing that actually works with these changes.

**Comment by nichmor** [comment]
> For the record, this new functionality does not actually work at all...at least not for the conda packages cache. If I set the `cache.conda-packages` in my config toml and/or set the `PIXI_CACHE_CONDA_PACKAGES_DIR` environment variable, it has absolutely no effect on where the conda packages are cached. The only thing it DOES seem to impact is the `pixi clean` command. If you set the environment variable and then do several `pixi install` that should cache many conda packages, nothing will ever appear in the configured cache dir...but then running `pixi clean cache --conda` will claim the cache was already clean because the clean seems to be the only thing that actually works with these changes.

hey! Thanks for the follow-up comment. Let me verify it.

**Comment by Vyrolan** [comment]
Thanks @nichmor   I tried it a bunch in a Linux environment and never could get it to cache conda packages according to the per-kind config.  All with latest pixi 0.70.2.  Using both our complex real env and with brand new dead-simple pixi.toml just installing one package.   I also tried with 0.70.2 on a Windows machine and had the same results.  I think the feature is awesome and was shocked the PR was only subtly mentioned as a fix in the release notes.
