### PR TITLE
fix: install Windows executable when executing `install.sh` in Git Bash

### LINKED ISSUE #965: How to install `pixi` in Git Bash environment?
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
# In Git Bash for Windows
uname -a
## MINGW64_NT-10.0-22631 MSI 3.4.9-be826601.x86_64 2023-09-07 12:36 UTC x86_64 Msys

curl -fsSL https://pixi.sh/install.sh | bash
## This script will automatically download and install Pixi (latest) for you.
## Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-MINGW64_NT-10.0-22631.tar.gz
## The binary will be installed into '/c/Users/john/.pixi/bin'
## #################################################################################################### ############## 100.0%
## error: 'https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-MINGW64_NT-10.0-22631.tar.gz' is not available
```

### Issue description

I would like to use `pixi` in the Git Bash shell for Windows. Thus I followed the [installation instructions for macOS and Linux](https://github.com/prefix-dev/pixi?tab=readme-ov-file#macos-and-linux) because they use `bash`, whereas the [Windows installation instructions](https://github.com/prefix-dev/pixi?tab=readme-ov-file#windows) use `iwr` and `iex` (which don't exist in the PATH for Git Bash).

I'm willing to help troubleshoot the `pixi shell` issue in https://github.com/prefix-dev/pixi/issues/417 if I can get `pixi` installed easily.

### Expected behavior

I expected it to download and install a compatible ~~Linux~~ Windows release of `pixi` for use in Git Bash

### PR DESCRIPTION
**Pull request by jdblischak**
Closes #965 

This PR downloads and installs `pixi` in a Git Bash shell on Windows. I've updated `install.sh` to properly download the ~~Linux~~ Windows executable. ~~However, the command `chmod +x "$BIN_DIR/pixi"` doesn't work on Windows, so I can't run `pixi` after downloading it. Any ideas?~~

### CODE REVIEW

**Comment by wolfv** [comment]
Hmm, when you are on Windows, you should download the Windows binary. Or do I misunderstand something?

**Comment by wolfv** [comment]
The chmod stuff can likely be skipped on Windows.

**Comment by jdblischak** [comment]
> Hmm, when you are on Windows, you should download the Windows binary. Or do I misunderstand something?

Doh. Good point. I was the one misunderstanding something. Now I understand how this can work. I'll test and push an update

**Comment by jdblischak** [comment]
Ok, now I've got it working in Git Bash

```sh
bash install/install.sh
## This script will automatically download and install Pixi (latest) for you.
## Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-pc-windows-msvc.zip
## ################################################################################################################ 100.0%
## Archive:  /tmp/.pixi_install.uZMw2jaz
##   inflating: /c/Users/john/.pixi/bin/pixi.exe
## The 'pixi' binary is installed into '/c/Users/john/.pixi/bin'
## Updating '/c/Users/john/.bash_profile'
## Please restart or source your shell.

# in a new shell
pixi --version
## pixi 0.16.1

ls -l ~/.pixi/bin/
## total 26624
## -rwxr-xr-x 1 john 197121 27260928 Mar 11 13:21 pixi.exe*
```

**Comment by wolfv** [comment]
Cool! Then we just need to fix `pixi shell` next :)

**Comment by jdblischak** [comment]
I also confirmed that my updates to support Git Bash did not break a standard installation in Ubuntu:

```sh
bash install/install.sh
## This script will automatically download and install Pixi (latest) for you.
## Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
## ####################################################################################################### 100.0%
## The 'pixi' binary is installed into '/home/wsl/.pixi/bin'
## Updating '/home/wsl/.bashrc'
## Please restart or source your shell.

# In a new shell
pixi --version
## pixi 0.16.1
```

**Comment by jdblischak** [comment]
CI is green. Ready for review. Please let me know if you'd like me to rebase onto main

File: install/install.sh [hunk 1]
```diff
@@ -24,11 +26,15 @@ fi
...
+if [[ $(uname -o) == "Msys" ]]; then
+  EXTENSION="zip"
+fi
 
 if [[ $VERSION == "latest" ]]; then
-  DOWNLOAD_URL=https://github.com/${REPO}/releases/latest/download/${BINARY}.tar.gz
+  DOWNLOAD_URL=https://github.com/${REPO}/releases/latest/download/${BINARY}.${EXTENSION}
 else
-  DOWNLOAD_URL=https://github.com/${REPO}/releases/download/${VERSION}/${BINARY}.tar.gz
+  DOWNLOAD_URL=https://github.com/${REPO}/releases/download/${VERSION}/.${EXTENSION}
```
Comment (wolfv) [inline install/install.sh:37]: you remoevd `${BINARY}` here?

**Review by wolfv — CHANGES_REQUESTED** [review]

**Comment by wolfv** [comment]
Looks good, one small comment

File: install/install.sh (hunk 1 above)
Comment (jdblischak) [reply install/install.sh]: Good catch! I just pushed the fix. I also confirmed locally that I can install a specific version:

```sh
PIXI_VERSION=v0.15.2 PIXI_HOME=./pixi-test bash install/install.sh
## This script will automatically download and install Pixi (v0.15.2) for you.
## Getting it from this url: https://github.com/prefix-dev/pixi/releases/download/v0.15.2/pixi-x86_64-pc-windows-msvc.zip
## ################################################################################################################ 100.0%
## Archive:  /tmp/.pixi_install.1FxREbAp
##   inflating: ./pixi-test/bin/pixi.exe
## The 'pixi' binary is installed into './pixi-test/bin'

./pixi-test/bin/pixi.exe --version
## pixi 0.15.2
```

**Review by wolfv — APPROVED** [review]

**Comment by W1M0R** [comment]
Thank you @jdblischak and @wolfv, this is much appreciated.

I left a comment here that might offer a solution to the `pixi shell` issue, via the `pixi shell-hook --shell bash` method: https://github.com/prefix-dev/pixi/issues/417#issuecomment-2140735844
