### PR TITLE
fix: load lock file with dependency override

### LINKED ISSUE #4237: After using dependency-overrides, updating locking will appear every time pixi shell is used
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[workspace]
authors = [""]
channels = ["conda-forge"]
name = "3dgs"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.aliyun.com/pypi/simple"
extra-index-urls = ["https://mirrors.aliyun.com/pypi/simple", "https://pypi.tuna.tsinghua.edu.cn/simple", "https://pypi.mirrors.ustc.edu.cn/simple"]
index-strategy = "unsafe-best-match" 
dependency-overrides = {pyyaml = ">=5.4.1"}

[dependencies]
python = "3.9.*"

[pypi-dependencies]
scipy = ">=1.13.1, <2"
ffmpeg = ">=1.4, <2"
opencv-python = ">=4.11.0.86, <5"
ipykernel = ">=6.29.5, <7"
json-tricks = ">=3.17.3, <4"
ad-cloud-sdk = { version = ">=0.1.4.85, <0.2", extras = ["adrn"] }
werkzeug = "==2.0.3"
open3d = ">=0.16.0, <0.17"

[system-requirements]
libc = { family = "glibc", version = "2.31" }

```
pixi version = 5.0.2

### Issue description

Because ad-cloud-sdk package which include numpy confilct with open3d numpy version, so i use dependency-overrides setting, then i can use this python environment, but I found that whenever I use pixi shell, updating locking is triggered.

### Expected behavior

https://github.com/user-attachments/assets/0ba61780-cfa2-486a-8eab-48920e696e2a

### PR DESCRIPTION
**Pull request by HernandoR**
This pr trying to fix #4237;

I believe this issue is `verify_package_platform_satisfiability` did not consider the override options in environment. Hence concludes lock file can not satisfy the environment.

I added a test case for `test_good_satisfiability` which reflects this issue. Still thinking how to inject  override options into environment requirements

### CODE REVIEW

**Comment by HernandoR** [comment]
@nichmor can you take some time reviewing this?

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs [hunk 1]
```diff
@@ -1005,6 +1005,27 @@ pub(crate) async fn verify_package_platform_satisfiability(
         return Err(Box::new(PlatformUnsat::TooManyCondaPackages(Vec::new())));
     }
 
+    // get pypi-options dependency overrides
+    // we map it to name: requirement for latter matching
+    let dependency_overrides: indexmap::IndexMap<
+        uv_normalize::PackageName,
+        uv_distribution_types::Requirement,
```
Comment (tdejager) [inline crates/pixi_core/src/lock_file/satisfiability/mod.rs]: Lets lose the type hint :)

**Review by tdejager — CHANGES_REQUESTED** [review]

**Comment by tdejager** [comment]
Thanks @HernandoR I'll take a look tomorrow or Thursday :)

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs (hunk 1 above)
Comment (HernandoR) [reply crates/pixi_core/src/lock_file/satisfiability/mod.rs]: `indexmap::IndexMap` was required by `collect`. I'm moving the type hint there and minimize to `.collect::<Result<indexmap::IndexMap<_, _>, _>>()?;`.

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs [hunk 2]
```diff
@@ -1005,6 +1005,24 @@ pub(crate) async fn verify_package_platform_satisfiability(
         return Err(Box::new(PlatformUnsat::TooManyCondaPackages(Vec::new())));
     }
 
+    // get pypi-options dependency overrides
+    // we map it to name: requirement for latter matching
```
Comment (tdejager) [inline crates/pixi_core/src/lock_file/satisfiability/mod.rs]:
```suggestion
    // retrieve dependency-overrides
    // map it to (name => requirement) for later matching
```

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs [hunk 3]
```diff
@@ -1217,6 +1235,13 @@ pub(crate) async fn verify_package_platform_satisfiability(
                     {
                         Ok(Some(idx)) => {
                             let record = &locked_pypi_environment.records[idx];
+
+                            // use the overridden requirements if we specified
```
Comment (tdejager) [inline crates/pixi_core/src/lock_file/satisfiability/mod.rs]:
```suggestion
                            // use the overridden requirements if specified
```

**Review by tdejager — CHANGES_REQUESTED** [review]
Two more small nits.

**Comment by tdejager** [comment]
Yeah I verified the behavior with your test @HernandoR, and it seems to work!

Are you on linux by chance and can you verify if the original issue is fixed? I can't get it into a shape thats runnable on my macOS machine.

**Comment by HernandoR** [comment]
> Yeah I verified the behavior with your test @HernandoR, and it seems to work!
> 
> 
> 
> Are you on linux by chance and can you verify if the original issue is fixed? I can't get it into a shape thats runnable on my macOS machine.

My only Linux machine is my working computer which does not have a rust tool chain. I'll verify it on next release.

**Comment by HernandoR** [comment]
> Yeah I verified the behavior with your test @HernandoR, and it seems to work!
> 
> Are you on linux by chance and can you verify if the original issue is fixed? I can't get it into a shape thats runnable on my macOS machine.

@tdejager  I confirm it fixed the original issue on linux.

**Review by tdejager — APPROVED** [review]

**Comment by tdejager** [comment]
Excellent work again @HernandoR, there are not a lot of external contributors fixing bugs from features they have introduced, this is really extremely appreciated!
