### PR TITLE
fix: always show cursor after control+c

### LINKED ISSUE #1548: Cursor disapear after ctrl+c in a pixi menu
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Get a menu with pixi and then ctrl + c, this will make the cursor in the terminal disappear. 

https://github.com/prefix-dev/pixi/assets/19758978/c7725efa-9da4-40db-be81-190e04c9b223

### Issue description

When I ctrl + c on a pixi menu, this makes my cursor disappear. Likely some clean-up logic is needed. 

### Expected behavior

I want my cursor back :upside_down_face:

### PR DESCRIPTION
**Pull request by ruben-arts**
fixes #1548  #2625 

The issue is related to and fixed with help of https://github.com/console-rs/dialoguer/issues/77

### CODE REVIEW

**Comment by baszalmstra** [comment]
I remember we explicitly removed ctrl+c handler at some point. @tdejager do you remember why?

**Comment by wolfv** [comment]
We explicitly removed the CTRL+C handler in the `pixi shell` and the trampoline binaries because we want the underlying processes to handle CTRL+C. I am assuming that still works?

**Comment by wolfv** [comment]
Also you can use `ctrl_c` from tokio so we don't need additional deps, check `exec.rs`.

File: src/cli/run.rs [hunk 1]
```diff
@@ -326,6 +326,14 @@ fn disambiguate_task_interactive<'p>(
         ..ColorfulTheme::default()
     };
 
+    // Ignore CTRL+C in the dialoguer prompt so that it shows the cursor again.
+    ctrlc::set_handler(move || {
```
Comment (wolfv) [inline src/cli/run.rs:330]: I am still in favor of using tokio if we can make it work :)

Comment (ruben-arts) [reply src/cli/run.rs]: Changed it back

**Comment by ruben-arts** [comment]
I notice one weird thing with this change. It seems to work like I would expect when killing things run after this command. But canceling an install acts differently from cancelling a normal install:
image

This is repeatable for some reason, @wolfv or @baszalmstra would you know why that could happen? e.g. did I just introduce a terrible bug that my testing isn't verifying?

**Comment by wolfv** [comment]
This is what the docs say. I wonder if we're in this situation - and need to come up with our own way of killing the remaining threads.

Screenshot 2024-12-19 at 17 06 07

**Comment by Hofer-Julian** [comment]
This PR is ready for review.

I tried to react on ctrl-c via tokio as suggested by @wolfv, but I couldn't get it to work. In order to reset the cursor, one has to write to stdout, and as far as I can tell no print goes through in that context.

When using the `ctrl_c` crate, everything works as expected.

**Comment by ruben-arts** [comment]
I retested it and it did indeed fix the issues I had. So I'll merge it.

**Comment by wolfv** [comment]
> I tried to react on ctrl-c via tokio as suggested by @wolfv, but I couldn't get it to work. In order to reset the cursor, one has to write to stdout, and as far as I can tell no print goes through in that context.

Interesting. Even with `flush`? 

But - whatever works! :)

**Comment by Hofer-Julian** [comment]
> Interesting. Even with flush?

I didn't try flushing, but since stdout is line-buffered, it should still have worked with `println!`

**Comment by Hofer-Julian** [comment]
> Not sure if that is still true when the terminal is e.g. set into `raw` mode for the selector thing.

Mmmh interesting, will try flushing tomorrow

**Comment by Hofer-Julian** [comment]
Flushing doesn't help, unfortunately, let's stick with the `ctrlc` crate for now
