### PR TITLE
fix: Parse properly 'default' as environment Cli argument

### LINKED ISSUE #1170: pixi install -e default not working
```bash
pixi install -e default
  × unknown environment 'default'
```

The explicit installation of the default environment does not work.
This is relevant e.g. in the context of installing multiple environments in CI including the default.
```yaml
  - name: Set up pixi
    uses: prefix-dev/setup-pixi@19b5e6071f70a82d3c5741d7b3f98a71d192eb20
    with:
      environments: default py312
```

Is this intended?

### PR DESCRIPTION
**Pull request by olivier-lacroix**
Fixes #1170

### CODE REVIEW

File: src/project/manifest/environment.rs [hunk 1]
```diff
@@ -48,7 +48,7 @@ impl EnvironmentName {
     /// to read from an environment variable, otherwise it will fall back to default
     pub fn from_arg_or_env_var(arg_name: Option<String>) -> Self {
         if let Some(arg_name) = arg_name {
-            return EnvironmentName::Named(arg_name);
+            return EnvironmentName::from_str(&arg_name).unwrap();
```
Comment (baszalmstra) [inline src/project/manifest/environment.rs:51]: I dont thinks its appropriate to unwrap here. If the user specifies a name with an underscore this will crash.

**Review by baszalmstra — CHANGES_REQUESTED** [review]

File: src/project/manifest/environment.rs (hunk 1 above)
Comment (olivier-lacroix) [reply src/project/manifest/environment.rs:51]: Fair enough :-)

**Comment by olivier-lacroix** [comment]
@baszalmstra this one is good for your review

**Review by ruben-arts — APPROVED** [review]
