### PR TITLE
fix: editability check during pypi install

### LINKED ISSUE #5604: Local dependency not installed as editable
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

Commands I ran and their output:
```shell
$ tree
.
├── pixi.lock
├── pyproject.toml
└── src
    └── myproject
        └── __init__.py

$ pixi list
Name                Version    Build                     Size  Kind   Source
bzip2               1.0.8      hd037594_9          121.91 KiB  conda  https://conda.anaconda.org/conda-forge
...
myproject           0.1.0                                      pypi
ncurses             6.5        h5e97a16_3          778.35 KiB  conda  https://conda.anaconda.org/conda-forge
openssl             3.6.1      hd24854e_1            2.96 MiB  conda  https://conda.anaconda.org/conda-forge
python              3.14.3     h4c637c5_101_cp314   12.90 MiB  conda  https://conda.anaconda.org/conda-forge
python_abi          3.14       8_cp314               6.83 KiB  conda  https://conda.anaconda.org/conda-forge
readline            8.3        h46df422_0          306.57 KiB  conda  https://conda.anaconda.org/conda-forge
requests            2.32.5                         199.50 KiB  pypi   requests-2.32.5-py3-none-any.whl

$ pixi list -e mydep
Environment: mydep
Name                Version      Build                     Size  Kind   Source
bzip2               1.0.8        hd037594_9          121.91 KiB  conda  https://conda.anaconda.org/conda-forge
...
libzlib             1.3.1        h8359307_2           45.35 KiB  conda  https://conda.anaconda.org/conda-forge
myproject           0.1.0                                        pypi
ncurses             6.5          h5e97a16_3          778.35 KiB  conda  https://conda.anaconda.org/conda-forge
openssl             3.6.1        hd24854e_1            2.96 MiB  conda  https://conda.anaconda.org/conda-forge
python              3.14.3       h4c637c5_101_cp314   12.90 MiB  conda  https://conda.anaconda.org/conda-forge
python_abi          3.14         8_cp314               6.83 KiB  conda  https://conda.anaconda.org/conda-forge
readline            8.3          h46df422_0          306.57 KiB  conda  https://conda.anaconda.org/conda-forge
requests            2.33.0.dev1                                  pypi

$ ls -1 .pixi/envs/mydep/lib/python3.14/site-packages
_myproject.pth
certifi
certifi-2026.2.25.dist-info
charset_normalizer
charset_normalizer-3.4.4.dist-info
conda-site.pth
idna
idna-3.11.dist-info
myproject-0.1.0.dist-info
README.txt
requests
requests-2.33.0.dev1.dist-info
urllib3
urllib3-2.6.3.dist-info

```
`pixi.toml`/`pyproject.toml` file that reproduces my issue:
```toml
[project]
dependencies = ["requests"]
name = "myproject"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
myproject = { path = ".", editable = true }

[tool.pixi.feature.mydep.pypi-dependencies]
requests = { path = "../requests", editable = true }

[tool.pixi.environments]
mydep = ["mydep"]
```
`pixi info` output:
```plaintext
System
------------
       Pixi version: 0.65.0
        TLS backend: rustls
           Platform: osx-arm64
   Virtual packages: __unix=0=0
                   : __osx=26.3=0
                   : __archspec=1=m1
          Cache dir: /Users/benber/Library/Caches/rattler/cache
       Auth storage: /Users/benber/.rattler/credentials.json
   Config locations: No config files found

Global
------------
            Bin dir: /Users/benber/.pixi/bin
    Environment dir: /Users/benber/.pixi/envs
       Manifest dir: /Users/benber/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: myproject
            Version: 0.1.0
      Manifest file: /Users/benber/Dev/conda/pixi-bugs/myproject/pyproject.toml
       Last updated: 04-03-2026 14:42:03

Environments
------------
        Environment: default
           Features: default
           Channels: conda-forge
   Dependency count: 1
       Dependencies: python
  PyPI Dependencies: myproject, requests
   Target platforms: osx-arm64
    Prefix location: /Users/benber/Dev/conda/pixi-bugs/myproject/.pixi/envs/default

        Environment: mydep
           Features: mydep, default
           Channels: conda-forge
   Dependency count: 1
       Dependencies: python
  PyPI Dependencies: requests, myproject
   Target platforms: osx-arm64
    Prefix location: /Users/benber/Dev/conda/pixi-bugs/myproject/.pixi/envs/mydep
```
Other files (e.g. script files, source files, etc.):

### Issue description

I'm trying to introduce pixi in a python project (project A) that depends on another one (project B).
They are both independent repositories.
It's very common to work on both at the same time.

I added the second project as an editable pypi dependency in a feature but noticed it's not an editable install.

I reproduced the issue with the above example using `requests`.
`requests` is a dependency of the main project. `pixi list` shows it's installed from pypi.

`pixi list -e mydep` shows it's installed from the local clone (`../requests`). All good but this isn't an editable install. It's a normal install from the path. There is no `.pth` for requests.

### Expected behavior

In the `mydep` environment, `requests` should be an editable install.

### PR DESCRIPTION
**Pull request by tdejager**
### Description

Fixes #5604 

This happened because the spec is duplicated and so both the registry `requests` and the local `requests` got passed into the solver. uv prefers the local one, so all good. However, we selected the *registry* requests version when determining editability. Now we just select by looking at all duplicates, as you cannot set editability directly in pep508 it should be good.

In the case of pixi features:

```toml
  [project]
  name = "myproject"
  version = "0.1.0"
  requires-python = ">= 3.11"
  dependencies = ["requests"]

  [build-system]
  build-backend = "hatchling.build"
  requires = ["hatchling"]

  [tool.pixi.workspace]
  channels = ["conda-forge"]
  platforms = ["osx-arm64"]

  [tool.pixi.pypi-dependencies]
  requests = { path = "./requests", editable = true }

  [tool.pixi.feature.prod.pypi-dependencies]
  requests = { path = "./requests", editable = false }

  [tool.pixi.environments]
  prod = ["prod"]
```

The `false` should be taken as it has higher precedence

### How Has This Been Tested?

Manually by using:

1. clone requests from github.

2. Use:
```toml
[project]
authors = [{name = "Tim de Jager", email = "tdejager89@gmail.com"}]
dependencies = ["requests"]
name = "5604"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
requests = { path = "./requests", editable = true }
```

3. run `pixi install` <-- Built version of pixi
4. Note the pth file is there for the dev version
```bash
/tmp/5604 is 📦 v0.1.0 via 🐍 took 57s
❯ ls .pixi/envs/default/lib/python3.14/site-packages/ | grep .pth
__editable__.requests-2.33.0.dev1.pth
```

5. With the *released* version of pixi this used a non-editable install.
6.  For the second, prod case, we see:

```bash
❯ ls .pixi/envs/prod/lib/python3.14/site-packages/ | grep .pth
conda-site.pth
```

### AI Disclosure

- [x] This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: Opus 4.6

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added sufficient tests to cover my changes.

### CODE REVIEW

File: crates/pixi_core/src/lock_file/update.rs [hunk 1]
```diff
@@ -2682,3 +2678,101 @@ async fn spawn_solve_pypi_task<'p>(
...
+/// feature priority ordering (non-default features come first) while also
+/// handling the same-feature case where a registry spec from
+/// `project.dependencies` lacks an editable field.
+fn is_editable_from_manifest(
+    manifest_pypi_deps: &pixi_manifest::PyPiDependencies,
+    package_name: &pep508_rs::PackageName,
+) -> bool {
+    manifest_pypi_deps
+        .get(package_name)
+        .and_then(|specs| specs.iter().find_map(|spec| spec.editable()))
```
Comment (tdejager) [inline crates/pixi_core/src/lock_file/update.rs:2697]: Note that `spec.editable` is an optional, so we are finding the first **set** value.
