### PR TITLE
Fix/shell prompt

### LINKED ISSUE #384: prompt not displaying in pixi shell
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

With `export PS1="${PIXI_PROMPT}${PS1}"` in `.bashrc`:

```
$ pixi shell
$
```

### Issue description

I assume this is because `$PIXI_PROMPT` is not defined when the `.bashrc` is sourced, because it seems defined in the temp file sourced after the shell is started. Following this logic, running `pixi shell` twice leads to the prompt appearing:

```
$ pixi shell
$ pixi shell
(prompt) $
```

### Expected behavior

```
$ pixi shell
(prompt) $
```

### PR DESCRIPTION
**Pull request by ruben-arts**
Depends on https://github.com/mamba-org/rattler/pull/375 to build

Changes the way the shell prompts are overwriten. These are now hard coded scripts per shell implementation. 

Closes #384

### CODE REVIEW

File: src/cli/mod.rs [hunk 1]
```diff
@@ -132,14 +107,20 @@ pub async fn execute() -> miette::Result<()> {
         clap_verbosity_flag::LevelFilter::Trace => LevelFilter::TRACE,
     };
 
+    // Default pixi level to warn but overwrite if a lower level is requested.
+    let pixi_level = if level_filter > LevelFilter::WARN {
+        level_filter
+    } else {
+        LevelFilter::WARN
+    };
```
Comment (baszalmstra) [inline src/cli/mod.rs:115]:
```suggestion
    let pixi_level = level_filter.max(LevelFilter::WARN);
```
