### PR TITLE
fix: preserve branch reference

### LINKED ISSUE #5185: pixi.lock always outdated with multiple git pypi dependency specifying branches
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

`pixi.toml` file that works:
```toml
[workspace]
authors = ["author"]
channels = ["conda-forge"]
name = "pixi-git"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
svgdigitizer = {git = "https://github.com/echemdb/svgdigitizer.git", rev = "master"}
```

Commands I ran and their output:
```shell
$ pixi shell -v
 INFO pixi_core::lock_file::outdated: environment 'default' is out of date because it does not exist in the lock-file.
 INFO pixi_core::lock_file::update: resolved conda environment for environment 'default' 'linux-64' in 1s 274ms 166us 656ns
 INFO resolve_pypi{group=default platform=linux-64}: pixi_core::lock_file::resolve::pypi: there are no python packages installed by conda
 INFO pixi_core::lock_file::update: resolved pypi packages for environment 'default' 'linux-64' in 635ms 322us 720ns
 INFO pixi_install_pypi: Installed 63 packages in 23ms
 INFO pixi_install_pypi: finished in 36ms
 INFO pixi_core::lock_file::update: Installed environment 'default' in 244.096852ms
 INFO pixi_cli::shell: Starting shell: Bash(Bash)

$ exit
exit
$ pixi shell -v
 INFO pixi_core::lock_file::update: the lock-file is up-to-date
 INFO pixi_core::environment::conda_metadata: No update needed for the prefix file.
 INFO pixi_install_pypi: Nothing to do - finished in 0ms
 INFO pixi_core::lock_file::update: Installed environment 'default' in 7.834698ms
 INFO pixi_cli::shell: Starting shell: Bash(Bash)

$ pixi shell -v
 INFO pixi_core::lock_file::update: the lock-file is up-to-date
 INFO pixi_core::lock_file::update: Environment 'default' is up-to-date with lock file hash
 INFO pixi_cli::shell: Starting shell: Bash(Bash)

```

`pixi.toml` file that reproduces my issue:
```toml
[workspace]
authors = ["author"]
channels = ["conda-forge"]
name = "pixi-git"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
svgdigitizer = {git = "https://github.com/echemdb/svgdigitizer.git", rev = "master"}
ec-tools = {git = "https://github.com/echemdb/ec-tools.git"}
```
```shell
$ pixi shell -v
 INFO pixi_core::lock_file::outdated: the pypi dependencies of environment 'default' for platform linux-64 are out of date because the requirement 'ec-tools @ git+https://github.com/echemdb/ec-tools.git' could not be satisfied (required by '<environment>')
 INFO resolve_pypi{group=default platform=linux-64}: pixi_core::lock_file::resolve::pypi: there are no python packages installed by conda
 INFO pixi_core::lock_file::update: resolved pypi packages for environment 'default' 'linux-64' in 2s 895ms 154us 404ns
 INFO pixi_core::environment::conda_metadata: No update needed for the prefix file.
 INFO pixi_install_pypi: Installed 7 packages in 1ms
 INFO pixi_install_pypi: finished in 9ms
 INFO pixi_core::lock_file::update: Installed environment 'default' in 16.76553ms
 INFO pixi_cli::shell: Starting shell: Bash(Bash)

$ exit
exit
$ pixi shell -v
 INFO pixi_core::lock_file::outdated: the dependencies of environment 'default' for platform linux-64 are out of date because 'svgdigitizer' has mismatching git ref: 'master != HEAD'
 INFO pixi_core::lock_file::update: resolved conda environment for environment 'default' 'linux-64' in 1s 290ms 863us 375ns
 INFO resolve_pypi{group=default platform=linux-64}: pixi_core::lock_file::resolve::pypi: there are no python packages installed by conda
 INFO pixi_core::lock_file::update: resolved pypi packages for environment 'default' 'linux-64' in 386ms 873us 447ns
 INFO pixi_core::environment::conda_metadata: No update needed for the prefix file.
 INFO pixi_install_pypi: Nothing to do - finished in 0ms
 INFO pixi_core::lock_file::update: Installed environment 'default' in 7.072771ms
 INFO pixi_cli::shell: Starting shell: Bash(Bash)
```

`pixi info` output:
```plaintext
System
------------
       Pixi version: 0.62.1
        TLS backend: rustls
           Platform: linux-64
   Virtual packages: __unix=0=0
                   : __linux=6.17.12=0
                   : __glibc=2.42=0
                   : __archspec=1=zen4
          Cache dir: /home/user/.cache/rattler/cache
       Auth storage: /home/user/.rattler/credentials.json
   Config locations: No config files found

Global
------------
            Bin dir: /home/user/.pixi/bin
    Environment dir: /home/user/.pixi/envs
       Manifest dir: /home/user/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: pixi-git
            Version: 0.1.0
      Manifest file: /home/user/pixi-git/pixi.toml
       Last updated: 21-12-2025 21:59:32

Environments
------------
        Environment: default
           Features: default
           Channels: conda-forge
   Dependency count: 1
       Dependencies: python
  PyPI Dependencies: svgdigitizer, ec-tools
   Target platforms: linux-64
    Prefix location: /home/user/pixi-git/.pixi/envs/default
```

### Issue description

When specifying a branch for a git pypi dependency while having more than one of these dependencies, pixi always reports the pixi.lock being out-of-date even though nothing changed. This leads to reinstallation of the dependency every time the environment is activated.
It works correctly when no branch is specified.

### Expected behavior

Reinstallation should only happen after a change in the repository.

### PR DESCRIPTION
**Pull request by nichmor**
### Description

Another look at https://github.com/prefix-dev/pixi/pull/5187

Fixes #5185 

### AI Disclosure

- [x] This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: Claude

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added sufficient tests to cover my changes.
- [x] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

**Comment by ruben-arts** [comment]
This will still not fix the lockfile if it's out of date:

```toml
[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
svgdigitizer = {git = "https://github.com/echemdb/svgdigitizer.git"}
ec-tools = {git = "https://github.com/echemdb/ec-tools.git", branch = "main"}
```
Run `pixi install`, will create a proper lockfile
```toml
# Now remove main
ec-tools = {git = "https://github.com/echemdb/ec-tools.git"}
```
Run `pixi install`, will **not** update the lockfile
Run `pixi update`, will update the lockfile
```toml
# Now add main back
ec-tools = {git = "https://github.com/echemdb/ec-tools.git", branch = "main"}
```
Run `pixi install`, will **not** update the lockfile but does find it not satisfiable. This is the issue!
Run `pixi update` to update,  **this shouldn't be required**

File: crates/pixi_core/src/lock_file/resolve/pypi.rs [hunk 1]
```diff
@@ -579,9 +622,36 @@ pub async fn resolve_pypi(
 
         #[error(transparent)]
         GitUrlParse(#[from] uv_git_types::GitUrlParseError),
+        // #[error("{0}")]
```
Comment (ruben-arts) [inline crates/pixi_core/src/lock_file/resolve/pypi.rs]: Remove?

**Comment by ruben-arts** [comment]
Now it fixes the issue when switching the branch, but there is still some weird behavior when using `rev`

It always adds the `rev` for the default branch:
```toml
ec-tools = {git = "https://github.com/echemdb/ec-tools.git"}
```
```yaml
      - pypi: git+https://github.com/echemdb/ec-tools.git?rev=693f4bef9243d06849cd807e866ed03562d30bb8#693f4bef9243d06849cd807e866ed03562d30bb8
```

If you change the `rev` to something else, it will lock that and it will never invalidate:
```toml
ec-tools = {git = "https://github.com/echemdb/ec-tools.git", rev = "main"}
```
`pixi install` results in:
```yaml
      - pypi: git+https://github.com/echemdb/ec-tools.git?rev=main#693f4bef9243d06849cd807e866ed03562d30bb8
```
now removing the `rev` from the `pixi.toml`:
```toml
ec-tools = {git = "https://github.com/echemdb/ec-tools.git"}
```
`pixi install` again the `rev=main` stays in the lockfile.
```yaml
      - pypi: git+https://github.com/echemdb/ec-tools.git?rev=main#693f4bef9243d06849cd807e866ed03562d30bb8
```

**Comment by tdejager** [comment]
Please fill out the AI section :)

File: crates/pixi_core/src/lock_file/resolve/pypi.rs [hunk 2]
```diff
@@ -347,7 +346,51 @@ pub async fn resolve_pypi(
...
+
+                let display_safe_url = pinned_git_spec.git.clone().into();
+
+                let repository_url = RepositoryUrl::new(&display_safe_url);
+                let reference = RepositoryReference {
+                    url: repository_url,
+                    reference: uv_reference,
+                };
+
+                tracing::debug!("Pre-populating git resolver: {:?} -> {}", reference, uv_sha);
```
Comment (tdejager) [inline crates/pixi_core/src/lock_file/resolve/pypi.rs]:
```suggestion
                tracing::debug!("pre-populating git resolver: {:?} -> {}", reference, uv_sha);
```

**Comment by tdejager** [comment]
Can you please comment and resolve rubens suggestions? :)

**Comment by nichmor** [comment]
tested all use-cases that are mentioned in the PR ( also between rev <-> tag ). Works as expected.
