### PR TITLE
fix: Create conda-meta/history file

### LINKED ISSUE #993: `conda run -p .pixi/envs/default` fails with `DirectoryNotACondaEnvironmentError`
```
❯ conda run -vv -p /Users/pavel/quantco/polarify/.pixi/envs/default echo hello
DEBUG conda.gateways.logging:set_verbosity(236): verbosity set to 2
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1125, in __call__
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 86, in main_subshell
    exit_code = do_call(args, p)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/cli/main_run.py", line 23, in execute
    validate_prefix(context.target_prefix or os.getenv("CONDA_PREFIX") or context.root_prefix),
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/cli/common.py", line 254, in validate_prefix
    raise DirectoryNotACondaEnvironmentError(prefix)
conda.exceptions.DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: /Users/pavel/quantco/polarify/.pixi/envs/default


❯ touch .pixi/envs/default/conda-meta/history
❯ conda run -vv -p /Users/pavel/quantco/polarify/.pixi/envs/default echo hello
DEBUG conda.gateways.logging:set_verbosity(236): verbosity set to 2
DEBUG conda.gateways.subprocess:subprocess_call(78): executing>> /bin/bash /var/folders/rz/q1r4tv0n6ll38q18fbk419mc0000gn/T/tmp52fwpypy
hello
```

Looking at the corresponding source code in conda:

```
def validate_prefix(prefix):
    """Verifies the prefix is a valid conda environment.

    :raises EnvironmentLocationNotFound: Non-existent path or not a directory.
    :raises DirectoryNotACondaEnvironmentError: Directory is not a conda environment.
    :returns: Valid prefix.
    :rtype: str
    """
    if isdir(prefix):
        if not isfile(join(prefix, 'conda-meta', 'history')):
            raise DirectoryNotACondaEnvironmentError(prefix)
    else:
        raise EnvironmentLocationNotFound(prefix)

    return prefix
```

If we add `history` to `conda-meta`, conda recognizes it as a conda environment.
This is relevant for using the vscode testing suite as it calls something like

```
conda run -p ./.pixi/envs/default --no-capture-output python ~/.vscode/extensions/ms-python.python-2024.2.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.2.1/pythonFiles/vscode_pytest/run_pytest_script.py --rootdir=.
```

Adding a comment (maybe even in the `history` file) why we need to create it would be sensible for pixi case IMO.

xref https://github.com/prefix-dev/pixi/discussions/415#discussioncomment-8807394

### PR DESCRIPTION
**Pull request by pavelzw**
Closes #993

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]

File: tests/install_tests.rs [hunk 1]
```diff
@@ -336,3 +336,16 @@ async fn test_channels_changed() {
     let lock_file = pixi.up_to_date_lock_file().await.unwrap();
     assert!(lock_file.contains_match_spec(DEFAULT_ENVIRONMENT_NAME, platform, "bar ==1"));
 }
+
+#[tokio::test]
```
Comment (ruben-arts) [inline tests/install_tests.rs:340]:
```suggestion
#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
#[serial]
#[cfg_attr(not(feature = "slow_integration_tests"), ignore)]
```
Actually installing is known to be flaky and slow. So we add these to prevent them from being run in the pre-push hooks and avoid flackiness.

File: src/environment.rs [hunk 2]
```diff
@@ -62,7 +62,7 @@ pub fn verify_prefix_location_unchanged(environment_dir: &Path) -> miette::Resul
 }
 
 /// Create the prefix location file.
-/// Give it the environment path to place it.
+/// This file is needed for `conda run -p .pixi/envs/<env>` to work.
```
Comment (ruben-arts) [inline src/environment.rs:65]: Is this true? We actually don't expect `conda` to do anything with this. This is done as a copy protection mechanism. 
If you miss interpreted it just remove it, as my comment was also unusual for our code base.
```suggestion
```

**Review by ruben-arts — COMMENTED** [review]
Thanks @pavelzw !

File: src/environment.rs (hunk 2 above)
Comment (pavelzw) [reply src/environment.rs:65]: Oops, the comment belongs to the function below

**Review by ruben-arts — APPROVED** [review]
Merci @pavelzw

**Comment by moritzwilksch** [comment]
Just noticed that when I manually touch `.pixi/envs/default/conda-meta/history`, a subsequent call to `pixi install` fails with
```
➜  repo git:(main) pixi install
  × failed to determine the currently installed packages for 'default'
  ╰─▶ EOF while parsing a value at line 1 column 0
```

**Comment by wolfv** [comment]
@moritzwilksch that is a bug that was fixed recently.

**Comment by moritzwilksch** [comment]
ahh I see, thank you!
