### PR TITLE
fix: indicate pixi self-update in requires-pixi error message

### LINKED ISSUE #5293: Error message from `requires-pixi` should indicate the existence of `pixi self-update`
### Problem description

```
> pixi install
Error:   × workspace requires pixi '==0.62.2', but I am 0.62.1
```

This should say something like "Try running `pixi self-update --version 0.62.2`"

### PR DESCRIPTION
**Pull request by varun-kht**
## Description

This PR improves the `requires-pixi` error message by suggesting `pixi self-update`
only when the self-update feature is enabled, and providing generic upgrade guidance
otherwise.

Fixes #5293

## How Has This Been Tested?

Manually verified the error output by triggering the `requires-pixi` version
mismatch locally and confirming the correct guidance is shown depending on
whether the `self_update` feature is enabled.

## AI Disclosure

- [ ] This PR contains AI-assisted content.
- [ ] I have reviewed and tested all AI-assisted changes.
- [ ] I take responsibility for all AI-assisted content in this PR.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [ ] I have made corresponding changes to the documentation 
- [ ] I have added sufficient tests to cover my changes 
- [ ] I have verified that changes impacting the JSON schema have been made in schema/model.py.

### CODE REVIEW

File: crates/pixi_cli/src/workspace/requires_pixi/verify.rs [hunk 1]
```diff
@@ -16,6 +16,22 @@ pub async fn execute(workspace: Workspace) -> miette::Result<()> {
...
+                    eprintln!();
+                    eprintln!("Try running:\n  pixi self-update");
+                }
+
+                #[cfg(not(feature = "self_update"))]
+                {
+                    eprintln!();
+                    eprintln!(
+                        "Please update pixi using your system package manager or reinstall it.\n\
+             See: https://pixi.sh/install"
```
Comment (ruben-arts) [inline crates/pixi_cli/src/workspace/requires_pixi/verify.rs]: Maybe you meant:

```suggestion
             See: https://pixi.sh/latest/installation/"
```
