### PR TITLE
fix: actually add the template and give better errors

### LINKED ISSUE #487: pixi init . does not modify the .gitignore if it is already present
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I tested this on Ubuntu 22.04 on WSL2 with pixi 0.7.0 :

```shell
traversaro@IITICUBLAP257:~$ mkdir testdir
traversaro@IITICUBLAP257:~$ cd testdir/
traversaro@IITICUBLAP257:~/testdir$ touch .gitignore
traversaro@IITICUBLAP257:~/testdir$ pixi init .
✔ Initialized project in /home/traversaro/testdir/.
traversaro@IITICUBLAP257:~/testdir$ cat .gitignore
```

### Issue description

From https://github.com/prefix-dev/pixi/issues/343#issuecomment-1739072486, I tought that `pixi init .`  should append a line related to .pixi directory even if the .gitignore is already present. However, this does not seem the case.

Smaller note, the comment in https://github.com/prefix-dev/pixi/blob/ac8bbf3aa945d4486a01b12f27788ec2050f5ecb/src/cli/init.rs#L116 seems outdated.

### Expected behavior

```shell
traversaro@IITICUBLAP257:~$ mkdir testdir
traversaro@IITICUBLAP257:~$ cd testdir/
traversaro@IITICUBLAP257:~/testdir$ touch .gitignore
traversaro@IITICUBLAP257:~/testdir$ pixi init .
✔ Initialized project in /home/traversaro/testdir/.
traversaro@IITICUBLAP257:~/testdir$ cat .gitignore
# pixi environments
.pixi
```

### PR DESCRIPTION
**Pull request by ruben-arts**
closes #487

### CODE REVIEW

File: src/cli/init.rs [hunk 1]
```diff
@@ -129,17 +141,14 @@ pub async fn execute(args: Args) -> miette::Result<()> {
...
-    let content = fs::read_to_string(path).unwrap_or_default();
-    search.lines().any(|line| content.contains(line))
-}
-
 // When the specific template is not in the file or the file does not exist.
 // Make the file and append the template to the file.
 fn create_or_append_file(path: &Path, template: &str) -> miette::Result<()> {
-    if !path.is_file() || !string_in_file(path, template) {
+    let file = fs::read_to_string(path)
+        .into_diagnostic()
```
Comment (baszalmstra) [inline src/cli/init.rs:148]: no need to turn this into a diagnostic first if you ignore the error anyway.

**Review by baszalmstra — APPROVED** [review]
