### PR TITLE
fix: Allow dots in global environment names

### LINKED ISSUE #3171: Feature names are allowed to contain a `.` but causes a parser error after being added.
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init --format pyproject
pixi add -f test.test rich
```

Output:

```
✔ Added rich
Added these only for feature: test.test
Error: 
  × Unexpected keys, expected only 'platforms', 'channels', 'channel-priority', 'target', 'dependencies', 'host-dependencies', 'build-dependencies', 'pypi-dependencies', 'activation', 'tasks',
  │ 'pypi-options', 'system-requirements'
    ╭─[pyproject.toml:37:25]
 36 │ 
 37 │ [tool.pixi.feature.test.test.dependencies]
    ·                         ──┬─
    ·                           ╰── 'test' was not expected here
 38 │ rich = "*"
    ╰────
  help: Did you mean 'tasks'?
```

### Issue description

It allows you to use a `.` in feature names but this results in a parser error after the feature is added.

### Expected behavior

The add command should check for illegal characters and return an error or escape it.

### LINKED ISSUE #4219: `pixi global install my.package` panics
```
root@a501ed6b249c:/# pixi global install my.package

thread 'main2' panicked at /home/runner/work/pixi/pixi/src/cli/global/install.rs:110:26:
valid environment name: ParseEnvironmentNameError { attempted_parse: "my.package" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at src/main.rs:49:10:
Tokio executor failed, was there a panic?: Any { .. }
```

this is because of the dot in the name

### PR DESCRIPTION
**Pull request by baszalmstra**
## Summary
- Fixes #4219 by updating the EnvironmentName regex to allow dots in package names
- **Also fixes #3171** by implementing proper TOML key quoting for identifiers with special characters
- Changes regex pattern from `^[a-z0-9-_]+$` to `^[a-z0-9-_.]+$`  
- Updates error message to include dots in allowed characters
- Refactors TOML manipulation to use key arrays instead of string splitting, enabling automatic key quoting
- Adds comprehensive tests for environment name parsing with dots

## Issues Fixed
- **#4219**: `pixi global install my.package` panics due to dots in package names
- **#3171**: Feature names with dots (`pixi add -f test.test rich`) cause TOML parser errors

## Key Changes
1. **Environment Name Validation**: Updated regex to allow dots in environment/package names
2. **TOML Key Handling**: Refactored from string-based to key array-based TOML manipulation
3. **Automatic Key Quoting**: Keys with special characters (like dots) are now properly quoted in TOML output

### Issue #4219 - Global Package Names
**Before**: `pixi global install my.package` → **Panic**  
**After**: `pixi global install my.package` → **Works correctly**

### Issue #3171 - Feature Names  
**Before**: `pixi add -f test.test rich` → Generates invalid TOML:
```toml
[tool.pixi.feature.test.test.dependencies]  # Invalid: unquoted key with dots
rich = "*"
```

**After**: `pixi add -f test.test rich` → Generates valid TOML:
```toml
[tool.pixi.feature."test.test".dependencies]  # Valid: properly quoted key
rich = "*"
```

## Test plan
- [x] Added test `test_environment_name_parsing()` that verifies:
  - Basic characters (letters, numbers, dashes, underscores) still work
  - Package names with dots like `my.package` and `package.with.dots` now work
  - Invalid characters (spaces, uppercase, special chars) are still rejected
- [x] Added comprehensive TOML key quoting tests for both issues
- [x] Verified fix works for both nested table and inline table formats
- [x] Existing tests pass with pre-commit hooks
- [x] Manual verification that both `pixi global install my.package` and `pixi add -f test.test rich` work correctly

This change enables users to:
1. Install global packages with dots in their names without panics
2. Use feature names with dots without TOML parsing errors
3. Use any identifiers with special TOML characters safely

### CODE REVIEW

**Comment by baszalmstra** [comment]
Its never just this easy ;)

File: crates/pixi_core/src/global/project/manifest.rs [hunk 1]
```diff
@@ -98,9 +111,10 @@ impl Manifest {
         );
 
         // Update self.document
+        let env_key = self.env_key(env_name, None);
         let channels_array = self
             .document
-            .get_or_insert_toml_array_mut(&format!("envs.{env_name}"), "channels")?;
+            .get_or_insert_toml_array_mut(&env_key, "channels")?;
```
Comment (baszalmstra) [inline crates/pixi_core/src/global/project/manifest.rs]: Cant we modify the `get_or_insert_nested_table` function to accept a &[str] instead of a &str? Then we dont need the helper function.

File: crates/pixi_manifest/src/toml/document.rs [hunk 2]
```diff
@@ -69,10 +69,16 @@ impl TomlDocument {
         table_name: &str,
     ) -> Result<&'a mut dyn TableLike, TomlError> {
         let parts: Vec<&str> = table_name.split('.').collect();
+        self.get_or_insert_nested_table_from_keys(&parts)
+    }
 
+    pub fn get_or_insert_nested_table_from_keys<'a>(
```
Comment (baszalmstra) [inline crates/pixi_manifest/src/toml/document.rs]: Lets just remove `get_or_insert_nested_table`, and use `get_or_insert_nested_table_from_keys` instead everywhere. Then we can also just drop the `from_keys` suffix.

File: crates/pixi_manifest/src/toml/document.rs [hunk 3]
```diff
@@ -81,11 +87,46 @@ impl TomlDocument {
             }
             current_table = item
                 .as_table_like_mut()
-                .ok_or_else(|| TomlError::table_error(part, table_name))?;
+                .ok_or_else(|| TomlError::table_error(part, &keys.join(".")))?;
         }
         Ok(current_table)
     }
 
+    pub fn get_or_insert_toml_array_mut_from_keys<'a>(
```
Comment (baszalmstra) [inline crates/pixi_manifest/src/toml/document.rs]: Replace all existing helper functions with this new approach where we pass an array of keys instead of a string.

File: crates/pixi_manifest/src/toml/document.rs [hunk 4]
```diff
@@ -81,11 +87,46 @@ impl TomlDocument {
...
+        array_name: &str,
+    ) -> Result<&'a mut Array, TomlError> {
+        self.get_or_insert_nested_table_from_keys(keys)?
+            .entry(array_name)
+            .or_insert(Item::Value(Value::Array(Array::new())))
+            .as_array_mut()
+            .ok_or_else(|| TomlError::array_error(array_name, &keys.join(".")))
+    }
+
+    pub fn insert_into_inline_table_from_keys<'a>(
```
Comment (baszalmstra) [inline crates/pixi_manifest/src/toml/document.rs]: Same for this helper function.

File: crates/pixi_manifest/src/toml/document.rs [hunk 5]
```diff
@@ -81,11 +87,46 @@ impl TomlDocument {
...
+    ) -> Result<&'a mut dyn TableLike, TomlError> {
+        let table = self.get_or_insert_nested_table_from_keys(keys)?;
+        
+        // Insert the value into the table
+        table.insert(key, Item::Value(value));
+        
+        Ok(table)
+    }
+
+    pub fn get_mut_toml_array_from_keys<'a>(
```
Comment (baszalmstra) [inline crates/pixi_manifest/src/toml/document.rs]: And this one.

File: crates/pixi_manifest/src/toml/document.rs [hunk 6]
```diff
@@ -110,68 +72,59 @@ impl TomlDocument {
             }
             current_table = item
                 .as_table_like_mut()
-                .ok_or_else(|| TomlError::table_error(part, table_name))?;
-        }
-
-        // Add dependency as inline table if it doesn't exist
-        if let Some(last) = last {
```
Comment (baszalmstra) [inline crates/pixi_manifest/src/toml/document.rs:117]: This logic is now missing, I think its important. Can you add it back and add a test to make sure that this works as expected? This also seems to be the cause of the change to the `crates/pixi_core/src/global/project/snapshots/pixi_core__global__project__manifest__tests__add_dependency.snap`

**Comment by baszalmstra** [comment]
Accidentally fixed https://github.com/prefix-dev/pixi/issues/3171

File: crates/pixi_manifest/src/toml/document.rs [hunk 7]
```diff
@@ -247,9 +230,123 @@ channels = ["dummy-channel"]
...
+            .insert_into_inline_table(
+                &["envs", "sdl.example", "dependencies"],
+                "test",
+                toml_edit::Value::from("1.0"),
+            )
+            .unwrap();
+
+        // Should create proper quoted section names
+        let result = manifest.0.to_string();
+        println!("Result: {}", result);
```
Comment (ruben-arts) [inline crates/pixi_manifest/src/toml/document.rs:277]: Let's remove all `println`'s from the tests
