### PR TITLE
fix: solve false positive `ChannelPriorityCombinationError`

### LINKED ISSUE #4939: "Multiple channel priorities are not allowed in a single environment" when having an environment
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

Commands I ran and their output:
```shell
pixi install
Error:   × Multiple channel priorities are not allowed in a single environment    
```

`pixi.toml`/`pyproject.toml` file that reproduces my issue:
```toml
[workspace]
authors = ["Martin Jepsen <majp@ramboll.com>"]
channels = ["conda-forge"]
name = "sandbox"
channel-priority = "disabled"
platforms = ["win-64"]
version = "0.1.0"
requires-pixi = ">=0.59.0"

[tasks]

[dependencies]
python = "=3.13"

[environments]

default = {features = ["default"], solve-group = "default"}
```
`pixi info` output:
```plaintext
System
------------
       Pixi version: 0.59.0
           Platform: win-64
   Virtual packages: __win=10.0.26100=0
                   : __archspec=1=skylake
          Cache dir: C:\Users\majp\AppData\Local\rattler\cache
       Auth storage: C:\Users\majp\.rattler\credentials.json
   Config locations: C:\Users\majp\.pixi\config.toml

Global
------------
            Bin dir: C:\Users\majp\.pixi\bin
    Environment dir: C:\Users\majp\.pixi\envs
       Manifest dir: C:\Users\majp\.pixi\manifests\pixi-global.toml

Workspace
------------
               Name: sandbox
            Version: 0.1.0
      Manifest file: C:\Users\majp\development\sandbox\pixi.toml

Environments
------------
        Environment: default
           Features: default, default
        Solve group: default
           Channels: conda-forge
   Dependency count: 1
       Dependencies: python
   Target platforms: win-64
    Prefix location: C:\Users\majp\development\sandbox\.pixi\envs\default
```
Other files (e.g. script files, source files, etc.):

### Issue description

Whenever I have `channel-priority = "disabled"`, I get the error

```
Error:   × Multiple channel priorities are not allowed in a single environment
```

This also happens in multi-feature environments, both with and without per-feature channel priorities.

### Expected behavior

The solver should be able to create environments with channel priority disabled.

### PR DESCRIPTION
**Pull request by MartinJepsen**
### Description

Fixes #4939

### How Has This Been Tested?

Added tests myself. Ran `pixi run test-fast`.

### AI Disclosure

- [ x This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: {e.g., Claude, Codex, GitHub Copilot, ChatGPT, etc.}

GitHub Copilot. Used it to ask about how I could fix a logic bug I made in my initial attempt at `channel_priority()` that didn't handle `None` channel priorities. Tests are all hand-written.

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added sufficient tests to cover my changes.
- [x] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

**Comment by MartinJepsen** [comment]
I seems all the test failures come from 404 errors. I don't think it's related to my changes, but I'm not sure. Please help :-)

File: crates/pixi_core/src/workspace/environment.rs [hunk 1]
```diff
@@ -1026,4 +1026,95 @@ mod tests {
...
+
+            [environments]
+            test = ["feat1"]
+            "#;
+
+            let workspace = Workspace::from_str(Path::new("pixi.toml"), contents).unwrap();
+            let env = workspace.environment("test").unwrap();
+            let grouped_env = GroupedEnvironment::from(env);
+
+            // This should return an error because the features have conflicting channel-priorities
```
Comment (ruben-arts) [inline crates/pixi_core/src/workspace/environment.rs]:
```suggestion
            // This should not return an error because the default feature sets the priority
```

Comment (MartinJepsen) [reply crates/pixi_core/src/workspace/environment.rs]: Thx, was a bit too fast at copy pasting the cases there :-)

**Comment by MartinJepsen** [comment]
@ruben-arts I implemented your suggestion, let me know if I should squash commits. I couldn't find anything about it in the contribution guidelines.

File: crates/pixi_core/src/workspace/environment.rs [hunk 2]
```diff
@@ -1026,4 +1026,95 @@ mod tests {
...
+
+            [environments]
+            test = ["feat1"]
+            "#;
+
+            let workspace = Workspace::from_str(Path::new("pixi.toml"), contents).unwrap();
+            let env = workspace.environment("test").unwrap();
+            let grouped_env = GroupedEnvironment::from(env);
+
+            // This should return an error because both features have the same channel-priority
```
Comment (MartinJepsen) [inline crates/pixi_core/src/workspace/environment.rs]:
```suggestion
            // This should not return an error because both features have the same channel-priority
```

**Comment by MartinJepsen** [comment]
@ruben-arts Looks like that windows test is timing out. I can't rerun it. Is there anything I should do on my end?
