### PR TITLE
fix: comparison of None in git source subdir vs empty string

### LINKED ISSUE #5226: git rattler-build dependency w/o recipe forces constant updates of pixi.lock
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

Follow-up from #5175 

The below used to be broken in pixi 0.62.1, and is confirmed to be fixed in 0.62.2 thanks to #5178:

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python.git = "https://github.com/python/cpython"
python.subdirectory = "Tools/pixi-packages/asan"
```
```bash
$ pixi update
$ pixi s --locked  # OK in 0.62.2
```

However, numpy is still broken:

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = "*"
numpy.git = "https://github.com/numpy/numpy"
numpy.subdirectory = "pixi-packages/default"
```
```bash
$ pixi update
$ pixi s --locked  -v
```
> INFO pixi_core::lock_file::outdated: the dependencies of environment 'default' for platform osx-arm64 are out of date because the source location 'numpy' changed from 'https://github.com/numpy/numpy@917b5f530d8636151a707005d5552cdbddda068b' to 'https://github.com/numpy/numpy@917b5f530d8636151a707005d5552cdbddda068b'
> [...]

I *think* that the main difference between python and numpy is that the former uses a rattler-build recipe, whereas the latter just uses pixi.toml and `[package]` blocks?

The end goal is to have both at the same time:

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python.git = "https://github.com/python/cpython"
python.subdirectory = "Tools/pixi-packages/asan"
numpy.git = "https://github.com/numpy/numpy"
numpy.subdirectory = "pixi-packages/asan"
```

Note the difference between [numpy/pixi-packages/default](https://github.com/numpy/numpy/blob/main/pixi-packages/default/pixi.toml):
```toml
[package.host-dependencies]
python = "*"
```
and [numpy/pixi-packages/asan](https://github.com/numpy/numpy/blob/main/pixi-packages/asan/pixi.toml):
```toml
[package.host-dependencies]
python.git = "https://github.com/python/cpython"
python.subdirectory = "Tools/pixi-packages/asan"
python.rev = "8bb5b6e8ce61da41b5affd5eb12d9cc46b5af448"
```

CC @baszalmstra

### PR DESCRIPTION
**Pull request by wolfv**
### Description

This should fix #5226 - the git source had a empty string as subdirectory while the other one had `None` and thus they compared as not equal. 

### How Has This Been Tested?

I tested this with the numpy reproducer.

### AI Disclosure

All code was written by Mr. Claude

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added sufficient tests to cover my changes.
- [ ] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

File: crates/pixi_record/src/pinned_source.rs [hunk 1]
```diff
@@ -994,9 +994,9 @@ impl PinnedSourceSpec {
 impl Display for PinnedSourceSpec {
     fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
         match self {
-            PinnedSourceSpec::Path(spec) => write!(f, "{}", spec.path),
-            PinnedSourceSpec::Url(spec) => write!(f, "{}", spec.url),
-            PinnedSourceSpec::Git(spec) => write!(f, "{}@{}", spec.git, spec.source.commit),
```
Comment (wolfv) [inline crates/pixi_record/src/pinned_source.rs:999]: this just usese the formatter from Git Source instead.

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs [hunk 2]
```diff
@@ -1159,6 +1159,12 @@ async fn verify_source_metadata(
                 };
 
                 // Check if the build source location changed
+                tracing::debug!(
```
Comment (baszalmstra) [inline crates/pixi_core/src/lock_file/satisfiability/mod.rs]: Is this actually useful ?

File: crates/pixi_record/src/pinned_source.rs [hunk 3]
```diff
@@ -994,9 +994,9 @@ impl PinnedSourceSpec {
...
+            PinnedSourceSpec::Path(spec) => write!(f, "{}", spec),
+            PinnedSourceSpec::Url(spec) => write!(f, "{}", spec),
+            PinnedSourceSpec::Git(spec) => write!(f, "{}", spec),
```
Comment (baszalmstra) [inline crates/pixi_record/src/pinned_source.rs]: Should this be `write!(f, "{spec}")`

File: crates/pixi_core/src/lock_file/satisfiability/mod.rs (hunk 2 above)
Comment (wolfv) [reply crates/pixi_core/src/lock_file/satisfiability/mod.rs]: removed

File: crates/pixi_record/src/pinned_source.rs (hunk 3 above)
Comment (wolfv) [reply crates/pixi_record/src/pinned_source.rs]: good point!

**Comment by baszalmstra** [comment]
Im thinking to further avoid this issue, we could also type this correctly. Maybe we can just represent the root subdirectory as "" too? Or if we do want to makenthe distinction between not specified and empty we could add a new type?

**Comment by wolfv** [comment]
There are a few (serialization) failures now because e.g. `subdir: .` serializes to `None` now. I implemented normalization for the path (`./foobar == foobar == foobar/ == foobar/././//` etc.).

@baszalmstra do you know the impact of this? I don't think there will be a lot of `subdir: .` in the wild, so hopefully not a crazy amount of lockfile churn. Alternatively, we can do normalization only when comparing the subdirs and keep faithful serialization.

**Comment by benglewis** [comment]
@wolfv If you can get it to work with a `subdir`, I think that that would be great, but I must agree, as a person with a `git` sourced PyPI package in my `pixi` project's `pyproject.toml`, I do not have a `subdir`. If you can maybe merge the change with churn on `subdir` and address that issue in another PR later on, so that those like me who are facing the lock file issues now can get this fix in the next `pixi` version and those with the `subdir` may get a fix later on, I think that this would be the better approach 🙏  (Just my 2 cents as a user of `pixi`)

File: crates/pixi_spec/src/subdirectory.rs [hunk 4]
```diff
@@ -0,0 +1,355 @@
...
+        // Check if path is absolute.
+        // On Windows, `is_absolute()` only returns true for paths like `C:\...`,
+        // so we also need to check for Unix-style absolute paths starting with `/`.
+        if path.is_absolute() || path.to_string_lossy().starts_with('/') {
+            return Err(SubdirectoryError::AbsolutePath(
+                path.to_string_lossy().into_owned(),
+            ));
+        }
+
+        // Check for parent directory references
```
Comment (baszalmstra) [inline crates/pixi_spec/src/subdirectory.rs]: This is not really correct right. The subdirectory `a/../b` is still valid. We just cant let it "escape" the root.

Comment (wolfv) [reply crates/pixi_spec/src/subdirectory.rs]: Sure but do we ever want this? I thought failing on this would be fine
