### PR TITLE
fix: `pixi global sync` reports after each handled environment

### LINKED ISSUE #2697: `pixi global` should report after each environment instead after the whole operation
`pixi global sync` collects changes and only reports them at the end. It does that so that it can filter some of them. For example, there's no need to mention that you added a package if you afterward remove the whole environment.

However, at the moment, with `pixi global sync` we only report at the very end. By reporting after each environment is handled, we give earlier feedback while still removing redundant info.

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Fixes #2697

### CODE REVIEW

File: src/cli/global/sync.rs [hunk 1]
```diff
@@ -28,16 +28,20 @@ pub async fn execute(args: Args) -> miette::Result<()> {
     }
 
     let mut errors = Vec::new();
+    let mut has_changed = false;
```
Comment (wolfv) [inline src/cli/global/sync.rs:31]: The state changes variable changes should still be reported once (to report on pruned envs).

Comment (Hofer-Julian) [reply src/cli/global/sync.rs]: You are right, nice find!

I fixed the code and added a test for this.
