### PR TITLE
fix: attempt copying trampoline when hard-linking fails

### LINKED ISSUE #2462: Pixi trampolines exceed hard link limit on Amazon EFS
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi global install nvim

```
When a sufficient number of global environments are already installed, installations off additional global environments will fail with this error:
```
  x Too many links (os error 31)
```

### Issue description

The newly introduced trampolines in `pixi 0.35` have led to a failure on our Amazon EFS system because too many hard links are created.  EFS unfortunately has a hard limit of 177 hard links to one file, which is easily reached with only a few global environments.  We should have an option to disable hardlinking of trampolines so that they can be either soft linked or copied.

### Expected behavior

The expected behavior is for the global environment installation to work without errors.

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Fixes #2462

### CODE REVIEW

File: src/global/trampoline.rs [hunk 1]
```diff
@@ -354,9 +354,14 @@ impl Trampoline {
             .into_diagnostic()?;
         }
 
-        // Create a hard link to the shared trampoline binary
-        if !self.path().exists() {
-            tokio::fs::hard_link(self.trampoline_path(), self.path())
+        // If the path doesn't exist yet, create a hard link to the shared trampoline binary
+        // If creating a hard link doesn't succeed, try copying
```
Comment (nichmor) [inline src/global/trampoline.rs:358]: could we expand here the comment explaining for what specific use-case we are trying to fallback to copying?

Comment (Hofer-Julian) [reply src/global/trampoline.rs:358]: I mean there was one specific issue, but in general the use-case is to fall-back if hard-linking doesn't work :)

Comment (nichmor) [reply src/global/trampoline.rs:358]: I think it would be nice to mention that there could be a limit for nr of hardlinks so we are trying to fallback because of this, so for a new contributor it would be easier to understand why because `std::hard_link` is not super verbose about this kind of errors

Comment (Hofer-Julian) [reply src/global/trampoline.rs:358]: Fair enough, extended the comment
