### PR TITLE
fix: remove duplicate header

### LINKED ISSUE #4862: bug(exec): `pixi exec --list` prints heading twice
```
❯ pixi exec --list -s python -- python --version
The environment has 17 packages:
Package          Version    Build               Size
bzip2            1.0.8      hd037594_8          122.1 KiB
ca-certificates  2025.10.5  hbd8a1cb_0          152.3 KiB
icu              75.1       hfee45f7_0          11.3 MiB
libexpat         2.7.1      hec049ff_0          64.4 KiB
libffi           3.5.2      he5f378a_0          39.3 KiB
liblzma          5.8.1      h39f12f2_2          90.1 KiB
libmpdec         4.0.0      h5505292_0          70.1 KiB
libsqlite        3.50.4     h4237e3c_0          881.5 KiB
libzlib          1.3.1      h8359307_2          45.3 KiB
ncurses          6.5        h5e97a16_3          778.3 KiB
openssl          3.5.4      h5503f6c_0          2.9 MiB
python           3.14.0     h40d2674_102_cp314  13 MiB
python_abi       3.14       8_cp314             6.8 KiB
readline         8.2        h1d1bf99_2          246.4 KiB
tk               8.6.13     h892fb3f_2          3 MiB
tzdata           2025b      h78e105d_0          120.1 KiB
zstd             1.5.7      h6491c7d_2          390.6 KiB
Package          Version    Build               Size

Python 3.14.0
```

the second `Package          Version    Build               Size` should not be included in the output

### PR DESCRIPTION
**Pull request by aosen-xiong**
fixes #4862

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Thank you.

I commented at the original issue. Will convert this PR to a draft until we agreed on the approach.

File: crates/pixi_core/src/environment/list.rs [hunk 1]
```diff
@@ -65,6 +65,5 @@ pub fn print_package_table(packages: Vec<PackageToOutput>) -> Result<(), std::io
         )?;
     }
 
-    writeln!(writer, "{header}\n")?;
     writer.flush()
```
Comment (pavelzw) [inline crates/pixi_core/src/environment/list.rs:69]:
```suggestion
    writeln!(writer, "\n")?;
    writer.flush()
```

this will make the dependency list easier distinguishable from the actual output of the program

Comment (aosen-xiong) [reply crates/pixi_core/src/environment/list.rs:69]: Thanks!

**Comment by ruben-arts** [comment]
Thank you, I've added the color to align with pixi list. The code it to different to quickly reuse it in all places so I'll merge it like this
