### PR TITLE
fix: add check error message to remove uv dependencies

### LINKED ISSUE #1306: pixi remove python doesn't remove uv dependencies
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init bla
cd bla
pixi add python
pixi add --pypi flask
pixi remove python
```

### Issue description

We have a crash because pixi first removes Python, and then still tries to create a `uv` context (which needs a Python interpreter). 

I am not sure what we should do:

- Disallow removing `python` when `pypi-dependencies` are there
- Remove all `pypi-dependencies` when `python` gets removed (might destroy some work, we could add a yes/no prompt)
- Just keep the `uv` stuff as is?

I think right now I prefer option 1, actually.

### Expected behavior

Unsure, but don't crash!

### PR DESCRIPTION
**Pull request by Dozie2001**
Closes #1306

### CODE REVIEW

File: src/cli/remove.rs [hunk 1]
```diff
@@ -54,7 +76,13 @@ pub async fn execute(args: Args) -> miette::Result<()> {
                         "failed to remove PyPI dependency: '{}'",
                         name.as_source()
                     ))?;
+                removed_deps.push(name.as_source().to_string());
             }
+            eprintln!(
+                "{}Removed PyPI dependencies: {}",
+                console::style(console::Emoji("✔ ", "")).green(),
+                removed_deps.join(", ")
+            );
```
Comment (ruben-arts) [inline src/cli/remove.rs:85]: This results in printing which dependencies are removed twice.

File: src/cli/remove.rs [hunk 2]
```diff
@@ -40,8 +41,29 @@ pub async fn execute(args: Args) -> miette::Result<()> {
...
+                        "Cannot remove Python while PyPI dependencies exist. Please remove these PyPI dependencies first: {}",
+                        deps_list
+                    ));
+                }
+            }
+        }
+    }
     match dependency_type {
         DependencyType::PypiDependency => {
+            let mut removed_deps = Vec::new();
```
Comment (ruben-arts) [inline src/cli/remove.rs:66]: I believe you don't need this anymore?

**Review by ruben-arts — APPROVED** [review]
