### PR TITLE
fix: add reactivation to pixi shell

### LINKED ISSUE #326: pixi shell not re-activating after an `add` is executed
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi shell
pixi add eigen pkg-config
pkg-config --cflags eigen3
Package eigen3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `eigen3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'eigen3' found
```

This should work. Since it doesn't `meson` also doesn't pick up `pixi` installed `eigen`.

### Issue description

To get it to work one must manually set `PKG_CONFIG_PATH`:
```bash
pixi shell
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CONDA_PREFIX/share/pkgconfig
pkg-config --cflags eigen3
-I/home/<redacted>/.pixi/env/include/eigen3
```

### Expected behavior

`PKG_CONFIG_PATH` should be set by `pixi` when `pkg-config` is part of the environment. That is:

```bash
pixi init
pixi shell
pixi add pkg-config eigen
pkg-config --cflags eigen3
-I/home/<redacted>/.pixi/env/include/eigen3
```

### PR DESCRIPTION
**Pull request by wolfv**
TODO:

- [x] implement for bash
- [x] implement for fish

fixes #326 #977

### CODE REVIEW

File: src/shell_snippets/pixi-zsh.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    # get first argument
+    local first_arg="${args[1]}" # In zsh, array indices start at 1
+    local cmd="$PIXI_EXE $*"
+
+    # execute the command as is
+    eval $cmd
+
+    # if first_arg = add or remove, call pixi reactivate
+    case "$first_arg" in
+        "add"|"remove")
```
Comment (ruben-arts) [inline src/shell_snippets/pixi-zsh.sh:16]: I guess this should also happen on `pixi install`

**Comment by pavelzw** [comment]
not sure i like this behavior :/ seems a bit too hacky

**Comment by wolfv** [comment]
@pavelzw unfortunately there is not really a way around it and it's exactly what conda/mamba/micromamba do. The re-hashing is the crucial step...

**Comment by pavelzw** [comment]
Using direnv with `watch_file pixi.lock` should fix this issue.

**Comment by wolfv** [comment]
yeah, but not everyone uses direnv 😱 I think the change is reasonable enough, and also does something in `pixi shell`.

File: src/activation.rs [hunk 2]
```diff
@@ -40,6 +40,12 @@ impl Project {
                         version.to_string()
                     }),
             ),
+            (
+                format!("PIXI_EXE"),
+                std::env::current_exe()
+                    .map(|s| s.to_string_lossy().to_string())
+                    .unwrap_or("notfound".to_string()),
+            )
```
Comment (baszalmstra) [inline src/activation.rs]: Should we just not add this instead of adding `PIXI_EXE: "notfound"`

File: src/prompt.rs [hunk 3]
```diff
@@ -1,11 +1,13 @@
 /// Set default pixi prompt for the bash shell
 pub fn get_bash_prompt(env_name: &str) -> String {
```
Comment (baszalmstra) [inline src/prompt.rs:2]: Maybe we should rename this to `get_bash_init_script` or something. Its no longer just setting the PS1.

**Review by baszalmstra — COMMENTED** [review]
I do agree that this is a bit magic but I also dont see another way to solve this other than only printing a warning.

At the moment this now only works for shells other than zsh and bash. What if we add a check to `pixi add` and co to see if you are in a shell and print a warning if thats the case? That requires no magic and should help people that use _better_ shells for which no magic is (yet) implemented.

**Comment by wolfv** [comment]
I also tested this with `fish` and `nushell` and both do not seem to have the same problem as `bash` & `zsh`.

I did not test on Windows with

- git bash
- powershell
- cmd.exe

Not sure if these have the problem or not. In any case, even without testing those, I think it's a good change.

File: src/prompt.rs [hunk 4]
```diff
@@ -1,11 +1,13 @@
...
-    format!("export PS1=\"({}) $PS1\"", env_name)
+    format!("export PS1=\"({}) $PS1\"\n{}", env_name, include_str!("shell_snippets/pixi-bash.sh"))
+
 }
 
 /// Set default pixi prompt for the zsh shell
 pub fn get_zsh_prompt(env_name: &str) -> String {
```
[the remark this answers is not in the document]
Comment (wolfv) [reply src/prompt.rs]: fixed!

**Comment by wolfv** [comment]
I think as it stands it's a "strict improvement" over the current state. 
I would like to investigate complete shell restart on these commands (ideally when we see that e.g. the lockfile has changed).
I think on UNIX that would be possible. 

However, IMO we can merge this, open a new issue, and take it from there.
