### PR TITLE
fix: input globs normalisation and force reinstall

### LINKED ISSUE #4844: bug(global): `install --path` uses cached package even though source changed
I've noticed that on my machine and https://github.com/prefix-dev/pixi-gui, `pixi global install --path .` always uses the cached package instead of rebuilding even though the source code changed.

Adding `--force-reinstall` doesn't help either

### PR DESCRIPTION
**Pull request by nichmor**
### Description

This PR contains two fixes inside (and one improvement)
* glob path normalization. pixi-gui ( or any rattler-build) backend will report back paths `recipe/..` which would be ignored. Instead, they should be normalized as "" ( current dir ) for which we will use ** glob.
* `--force-reinstall` now indeed triggers entire source rebuild.
* Instead of explicitly using a temporary directory in `pixi build` ( which will bypass using cache ), we now cache the result of a build. This was discovered when testing the global install

Fixes #4844

### How Has This Been Tested?

* tested on pixi-gui repository.
* also with unit /integration tests

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added sufficient tests to cover my changes.

### CODE REVIEW

File: crates/pixi_cli/src/build.rs [hunk 1]
```diff
@@ -217,7 +210,6 @@ pub async fn execute(args: Args) -> miette::Result<()> {
         // If a simple rename fails (e.g., across filesystems), fall back to copy+remove.
         if let Err(_e) = fs_err::rename(&package_path, &dest_path) {
             fs_err::copy(&package_path, &dest_path).into_diagnostic()?;
-            fs_err::remove_file(&package_path).into_diagnostic()?;
```
Comment (nichmor) [inline crates/pixi_cli/src/build.rs:341]: We don't need to remove cached artefact

File: tests/integration_python/pixi_global/test_global.py [hunk 2]
```diff
@@ -2365,3 +2365,59 @@ def test_update_sync_conda_file(
             env=env,
             cwd=cwd,
         )
+
+
+@pytest.mark.slow
+def test_install_source_package_with_force_reinstall(
```
Comment (ruben-arts) [inline tests/integration_python/pixi_global/test_global.py:2371]: Can you reduce the impact of this test on our CI time, this is taking 16s where only one test is slower than that. 

Some ideas would be a really basic python package

**Review by ruben-arts — COMMENTED** [review]
I didn't test it yet but, could you take a look at the tests? The error seems related.

File: tests/integration_python/pixi_global/test_global.py (hunk 2 above)
Comment (nichmor) [reply tests/integration_python/pixi_global/test_global.py:2371]: only by moving this test to the pixi-integration-tests repo

Comment (baszalmstra) [inline tests/integration_python/pixi_global/test_global.py:2371]: Maybe we can make this test use the in-memory backend instead of actually installing something?

File: crates/pixi_build_backend_passthrough/src/lib.rs [hunk 3]
```diff
@@ -147,6 +149,7 @@ impl InMemoryBackend for PassthroughBackend {
         params: CondaBuildV1Params,
         _output_stream: &(dyn BackendOutputStream + Send + 'static),
     ) -> Result<CondaBuildV1Result, Box<CommunicationError>> {
+        eprintln!("PassthroughBackend: Starting conda_build_v1");
```
Comment (nichmor) [inline crates/pixi_build_backend_passthrough/src/lib.rs]: this is need to assert that we trigger/don't trigger rebuild

File: crates/pixi_build_backend_passthrough/src/lib.rs [hunk 4]
```diff
@@ -31,6 +31,15 @@ use serde::Deserialize;
 
 const BACKEND_NAME: &str = "passthrough";
 
+/// Events that can be emitted by the observable backend during method calls.
+#[derive(Debug, Clone, PartialEq, Eq)]
```
Comment (baszalmstra) [inline crates/pixi_build_backend_passthrough/src/lib.rs:35]:
```suggestion
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
```
