### PR TITLE
fix: operation was cancelled error

### LINKED ISSUE #5200: `the operation was cancelled` error while solving
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

Commands I ran and their output:
```shell
ros_workspace on  main 🧚  
➜ pixi i
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  took 23s 
❯ pixi i
Error:   × failed to solve requirements of environment 'default' for platform 'win-64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  
❯ pixi i
▪ solving              [────────────────────]  0/12                                                                                                                                                                                     
thread '<unnamed>' panicked at crates/pixi_command_dispatcher/src/command_dispatcher_processor/mod.rs:502:56:
invalid SlotMap key used
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  
❯ pixi i
▪ solving              [────────────────────]  0/13                                                                                                                                                                                     
thread '<unnamed>' panicked at crates/pixi_command_dispatcher/src/command_dispatcher_processor/mod.rs:502:56:
invalid SlotMap key used
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × failed to solve requirements of environment 'default' for platform 'win-64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  
❯ pixi i
▪ solving              [────────────────────]  0/13                                                                                                                                                                                     
thread '<unnamed>' panicked at crates/pixi_command_dispatcher/src/command_dispatcher_processor/mod.rs:502:56:
invalid SlotMap key used
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × failed to solve requirements of environment 'default' for platform 'linux-64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  
❯ pixi i
▪ solving              [────────────────────]  0/12                                                                                                                                                                                     
thread '<unnamed>' panicked at crates/pixi_command_dispatcher/src/command_dispatcher_processor/mod.rs:502:56:
invalid SlotMap key used
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × failed to solve requirements of environment 'default' for platform 'win-64'
  ╰─▶   ⚠ the operation was cancelled
      
ros_workspace on  main 🧚  
❯ pixi i
▪ fetching repodata    [━━━━━━━━━━━━━━━━━━━━] 
# here it's working but the above progressbar wasn't removed properly.
```
`pixi.toml`/`pyproject.toml` file that reproduces my issue:
It was on this GitHub repo's main branch: https://github.com/ruben-arts/ros_workspace
`pixi info` output:
```plaintext
➜ pixi info
System
------------
       Pixi version: 0.62.1
        TLS backend: rustls
           Platform: osx-arm64
   Virtual packages: __unix=0=0
                   : __osx=15.1.1=0
                   : __archspec=1=m1
          Cache dir: /Users/rubenarts/Library/Caches/rattler/cache
       Auth storage: /Users/rubenarts/.rattler/credentials.json
   Config locations: /Users/rubenarts/.pixi/config.toml /Users/rubenarts/Library/Application Support/pixi/config.toml

Global
------------
            Bin dir: /Users/rubenarts/.pixi/bin
    Environment dir: /Users/rubenarts/.pixi/envs
       Manifest dir: /Users/rubenarts/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: ros_workspace
      Manifest file: /Users/rubenarts/envs/ros_workspace/pixi.toml
       Last updated: 24-12-2025 09:03:56

Environments
------------
        Environment: default
           Features: default
           Channels: https://prefix.dev/pixi-build-backends, https://prefix.dev/conda-forge, https://prefix.dev/robostack-humble
   Dependency count: 5
       Dependencies: ros-humble-ros-core, ros-humble-turtlesim, ros-humble-navigator, ros-humble-navigator-py, ros-humble-talker-py
   Target platforms: linux-aarch64, win-64, osx-arm64, linux-64
    Prefix location: /Users/rubenarts/envs/ros_workspace/.pixi/envs/default
              Tasks: navigator_py, navigator, sim, talker
```

Ran it with a `main` build of Pixi.

### Issue description

Running `pixi install` multiple times, where the first 5 times it fails due to some non-informative error.

### Expected behavior

No error at all, as it is able to solve eventually.

### PR DESCRIPTION
**Pull request by baszalmstra**
### Description

This fixes the dreaded `operation was cancelled` error. This was caused by a race condition where an error cause the cancellation of another task which then raced quicker to the pixi frontend then the actual error. With this PR a coalesced task that errors sends the error to all pending tasks instead of only to one and cancelling the others. This ensures that an error is always returned to the frontend.

Fixes #5200

### How Has This Been Tested?

I tested this locally in a reproducer case that I happened to have.

### AI Disclosure
- [x] This PR contains AI-generated content.
  - [x] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: Claude Opus 4.5

### Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added sufficient tests to cover my changes.
- [ ] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

File: crates/pixi_core/src/lock_file/outdated.rs [hunk 1]
```diff
@@ -216,16 +218,20 @@ async fn find_unsatisfiable_targets<'p>(
             continue;
         }
 
-        // Verify each individual platform
+        // Verify each individual platform concurrently
+        let mut verify_futures = FuturesUnordered::new();
         for platform in platforms {
-            match verify_platform_satisfiability(
+            verify_futures.push(verify_platform_satisfiability(
```
Comment (baszalmstra) [inline crates/pixi_core/src/lock_file/outdated.rs]: This is a little bonus addition which parallelizes the satisfiability check of source dependencies for different environments.

**Review by tdejager — APPROVED** [review]
