### PR TITLE
fix: changing `package.build.config` does not invalidate caches

### LINKED ISSUE #5309: Changing `package.build.config` does not invalidate caches
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases/latest) of pixi, using `pixi --version`.

### Reproducible example

Check out this repository: https://github.com/baszalmstra/pixi-build-backend-config-invalidation-bug 

The package contains a noarch python project.

1. Clone https://github.com/baszalmstra/pixi-build-backend-config-invalidation-bug 
2. Run `pixi lock` once in the clone to populate caches. Lockfile should be up-to-date.
3. Comment in the following in the `pixi.toml` to make to package platform specific
    ```toml
    [package.build.config]
    noarch = false
    ```
4. Run `pixi lock` again. Note that the lock-file is still up-to-date, which is wrong.
5. Delete the cache folder. `rm -rf .pixi/build`
6. Rerun `pixi lock`. Note that the lock-file is updated.

### Issue description

I think the `package.build.config` section does not invalidate the backend cache.

### Expected behavior

The cache should be updated and the lock-file should have changed as soon as the package is made `noarch: false`.

### PR DESCRIPTION
**Pull request by baszalmstra**
### Description

This fixes an issue where changes to `[package.build.config]` in pixi.toml (such as `noarch = true` to `noarch = false`) would not invalidate the metadata cache, causing the lock file to appear up-to-date when it should have been re-solved.

The fix introduces a `ConfigurationHash` that captures changes to both the `configuration` and `target_configuration` fields from the build backend. This hash is now:
- Computed when creating metadata via `call_conda_outputs`
- Stored in `CachedCondaMetadata`
- Checked during cache freshness verification in `verify_cache_freshness`

When the configuration changes, the metadata cache is invalidated, triggering a re-query of the build backend and subsequent lock file update.

Fixes #5309

### How Has This Been Tested?

- [x] A manual check with the reproducer from the issue

### AI Disclosure

- [x] This PR contains AI-generated content.
  - [ ] I have tested any AI-generated content in my PR.
  - [x] I take responsibility for any AI-generated content in my PR.

Tools: Claude Code Opus 4.5

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added sufficient tests to cover my changes.
- [x] I have verified that changes that would impact the JSON schema have been made in `schema/model.py`.

### CODE REVIEW

File: crates/pixi_command_dispatcher/src/input_hash.rs [hunk 1]
```diff
@@ -14,3 +16,37 @@ impl From<&'_ ProjectModel> for ProjectModelHash {
...
+        target_configuration: Option<&OrderMap<TargetSelector, serde_json::Value>>,
+    ) -> Option<Self> {
+        // Only compute a hash if there's any configuration
+        if configuration.is_none() && target_configuration.is_none() {
+            return None;
+        }
+
+        let mut hasher = Xxh3::new();
+        StableHashBuilder::new()
+            .field("configuration", &configuration.map(StableJson::new))
```
Comment (ruben-arts) [inline crates/pixi_command_dispatcher/src/input_hash.rs]: What about calling all of this `config` as that represents the name in the `pixi.toml`?

File: crates/pixi_command_dispatcher/src/input_hash.rs [hunk 2]
```diff
@@ -14,3 +16,37 @@ impl From<&'_ ProjectModel> for ProjectModelHash {
...
+pub struct ConfigurationHash(u64);
+
+impl ConfigurationHash {
+    /// Computes a hash from the configuration and target configuration.
+    pub fn compute(
+        configuration: Option<&serde_json::Value>,
+        target_configuration: Option<&OrderMap<TargetSelector, serde_json::Value>>,
+    ) -> Option<Self> {
+        // Only compute a hash if there's any configuration
+        if configuration.is_none() && target_configuration.is_none() {
```
Comment (ruben-arts) [inline crates/pixi_command_dispatcher/src/input_hash.rs]: Nitpick: 

```toml
[package.build.config]
```
Adding or removing only this line triggers a rebuild. I guess that could be sanitized before this check, so that it doesn't trigger a resolve.

**Comment by baszalmstra** [comment]
@ruben-arts Should work now! 
@Hofer-Julian I added a test too!

**Comment by ruben-arts** [comment]
```diff
diff --git a/examples/pixi-build/cpp-sdl/pixi.toml b/examples/pixi-build/cpp-sdl/pixi.toml
index 868ed770c..4a52af73c 100644
--- a/examples/pixi-build/cpp-sdl/pixi.toml
+++ b/examples/pixi-build/cpp-sdl/pixi.toml
@@ -32,6 +32,7 @@ channels = [
 name = "pixi-build-cmake"
 version = "0.3.*"
 
+[package.build.config]
 
 [package.host-dependencies]
 # This ensures that SDL2 is available at build time.
```

This will still trigger a rebuild.

**Comment by baszalmstra** [comment]
@ruben-arts Are you sure you cleared the cache? There is a test that literally checks that.

**Comment by baszalmstra** [comment]
See: https://github.com/baszalmstra/pixi/blob/e2546d9768049903b285d6ec2ef2c3b388294035/crates/pixi/tests/integration_rust/build_tests.rs#L906

**Comment by baszalmstra** [comment]
@ruben-arts I just tried it myself and it seems to work for me!

**Comment by ruben-arts** [comment]
> @ruben-arts Are you sure you cleared the cache? There is a test that literally checks that.

 I did recheck with clean cache (`rm -rf examples/cpp-sdl/.pixi`) and rebuild of pixi itself, I can't make it work as expected. It seems like the test is only checking the lockfile satisfiablity but not te rebuilding request. 

Maybe this reproducer helps:
 ```
pixi install
# First build 👍 
pixi install
# Cached everything 👍 

echo "[package.build.config]" >> pixi.toml

pixi lock
# Statisfied 👍 

pixi install
# Unexpected Rebuild 👎 
```

**Comment by baszalmstra** [comment]
@ruben-arts OKE! Should be good now. :) All caches now use the same mechanism for the configuration.
